### ISSUE TITLE
enquoted filenames are not supported

### ISSUE THREAD

**Issue by lvmm** [thekid/inotify-win#40]
```
C:\temp>inotifywait.exe -m "C:\temp\1\"

Unhandled Exception: System.ArgumentException: Path does not exist: `C:\temp\1"`
   at De.Thekid.INotify.ArgumentParser.ParseArgument(String option, String[] args, Int32& i, Arguments result)
   at De.Thekid.INotify.ArgumentParser.Parse(String[] args)
   at De.Thekid.INotify.Runner.Main(String[] args)
```

and that, of course, means that one cannot watch files with spaces in names. Also if the file being watched is a directory there is no trailing [back]slash after its name like in linux inotifywait, so once this bug is fixed it won't be possible to determine whether the space is part of the name or a separator.

**Comment by thekid** [comment]
See #37
